swagger: "2.0"
info:
  title: goa_starterulator Service
  description: Service for adding numbers, a Goa teaser
  version: ""
host: localhost:8085
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /add/{a}/{b}:
    get:
      tags:
      - goa_starter
      summary: add goa_starter
      operationId: goa_starter#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        type: integer
      - name: b
        in: path
        description: Right operand
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /goa_starter-calc/{c}/{d}:
    get:
      tags:
      - goa_starter-calc
      summary: add goa_starter-calc
      operationId: goa_starter-calc#add
      parameters:
      - name: c
        in: path
        description: Left operand
        required: true
        type: integer
      - name: d
        in: path
        description: Right operand
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
